language: node_js
before_script: echo "Running tests against $(node -v)..."
script: npm test
after_script: npm run coverage && cat ./coverage/lcov.info | npx coveralls
notifications:
  email:
    - beaudry.justin+travis-ci@gmail.com
